jobs:
  - job: win32
    timeoutInMinutes: 90
    strategy:
      matrix:
        vs2017-x86-win2016:
          vmImage: vs2017-win2016
          VS_VER: "15"
          PLATFORM: "x86"
    pool:
      vmImage: $(vmImage)
    variables:
      DOWNLOAD_DIR: $(System.Workfolder)\_download_cache
      MSYS2_ROOT: $(System.Workfolder)\msys64
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'
      - script: |
          choco install msys2 --params="/InstallDir:%MSYS2_ROOT% /NoPath"
        displayName: Install MSYS2
      - script: |
          python.exe build.py build --msys-dir=%MSYS2_ROOT% --archives-download-dir=%DOWNLOAD_DIR% --platform=%PLATFORM% --vs-ver=%VS_VER% -k --enable-gi --py-wheel --py-egg --python-ver 3.7 enchant gtk gtk3-full pycairo pygobject lz4
